### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by DevinKott** [mattsch/badnest#12]
I followed the instructions to get my issue_token and cookie.

I think the issue_token is fine. However, the cookie is probably wrong. I followed the instructions, selected the last `iframe` call, under `Request Headers` here is my cookie:

`1P_JAR=2020-6-23-16; NID=....................; GAPS=.....................; __Host-GAPS=.................; SAPISID=.........; __Secure-HSID=...........; .........` and a bunch of others.

Yet when I restart home-assistant I get a notification saying that `badnest` integration could not be setup.

Any advice?

**Comment by mattsch** [comment]
Impossible for me to tell without sanitized config snippets and debug logs. You'll want to update your configuration.yaml and add:
```
    custom_components.badnest: debug                                                                                                                                 
    custom_components.badnest.camera: debug
```
To the `logger:` section and then add those logs here.

**Comment by DevinKott** [comment]
@mattsch I can do this in a bit, I'll get that information for you and comment it here soon. Thanks for the fast reply

**Comment by motamedn** [comment]
Any updates to this? Not sure if this looks right or not but this is from my home assistant log once I added those lines to my configuration.yaml under badnest.

`2020-06-29 12:29:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for badnest which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 12:29:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for lutron_caseta_pro which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 12:29:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 12:29:10 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry TP-Link Kasa for tplink
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyHS100/smartdevice.py", line 117, in _query_helper
    request=request,
  File "/usr/local/lib/python3.7/site-packages/pyHS100/protocol.py", line 47, in query
    sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/tplink/__init__.py", line 82, in async_setup_entry
    static_devices = get_static_devices(config_data)
  File "/usr/src/homeassistant/homeassistant/components/tplink/common.py", line 122, in get_static_devices
    for plug in SmartStrip(host).plugs.values():
  File "/usr/local/lib/python3.7/site-packages/pyHS100/smartstrip.py", line 43, in __init__
    children = self.sys_info["children"]
  File "/usr/local/lib/python3.7/site-packages/pyHS100/smartdevice.py", line 186, in sys_info
    return defaultdict(lambda: None, self.get_sysinfo())
  File "/usr/local/lib/python3.7/site-packages/pyHS100/smartdevice.py", line 196, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/usr/local/lib/python3.7/site-packages/pyHS100/smartdevice.py", line 120, in _query_helper
    raise SmartDeviceException('Communication error') from ex
pyHS100.smartdevice.SmartDeviceException: Communication error
2020-06-29 12:29:11 ERROR (MainThread) [homeassistant.setup] Error during setup of component badnest
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/badnest/__init__.py", line 34, in setup
    cookie,
  File "/config/custom_components/badnest/api.py", line 114, in __init__
    self.login()
  File "/config/custom_components/badnest/api.py", line 154, in login
    access_token = r.json()['access_token']
KeyError: 'access_token'
2020-06-29 12:29:11 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform badnest.sensor: Unable to set up component.
2020-06-29 12:29:11 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform badnest.climate: Unable to set up component.
2020-06-29 12:29:22 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.`

**Comment by mattsch** [comment]
No updates, the logs just show it wasn't able to login but no real reason otherwise. I'm guessing a copypasta issue for cookie or url but can't say beyond that. FWIW, I just had to regenerate mine so I know the process still works.

**Comment by cmatte** [comment]
Had the same issue and resolved just re-configuring issue_token and cookie as well.

**Comment by motamedn** [comment]
Same here. Thanks for everything Mattsch. Any idea on what triggers the need to reconfigure? Things were fine for a long time but I have had this happen like three times in a week.

**Comment by mattsch** [comment]
Not a clue. I've had it work fine for weeks, then boot me out a few times in a short span as well. I try to make sure and hit home.nest.com from the same browser once a week to see if that helps but I don't think it matters much.

**Comment by cmatte** [comment]
I have noticed a lot of short-living expiration for cookies reported when I did the setup, might be a way to counteract what we're doing here.

**Comment by nhusby** [comment]
I had the same thing happen to me.  I just solved it by re-doing the config process.  Be sure you are copying the REQUEST cookie, not the response cookie.  I started getting this error out of the blue and tried re-doing the config, but I think that was my mistake when re-doing it, is that I copied the response set-cookie header by mistake.

**Comment by DevinKott** [comment]
![error_log](https://user-images.githubusercontent.com/22530352/87234521-b0b3a100-c39f-11ea-986d-2fd6fa607504.png)
![screenshot4](https://user-images.githubusercontent.com/22530352/87234522-b14c3780-c39f-11ea-8b11-49de17fd00af.png)
![Screenshot from 2020-07-11 17-54-03](https://user-images.githubusercontent.com/22530352/87234523-b14c3780-c39f-11ea-8de2-aa78c8935b59.png)

I have attached some photos of the HA logs. I just retried to set the cookie and token, still no luck.

**Comment by DevinKott** [comment]
![Untitled](https://user-images.githubusercontent.com/22530352/87234552-13a53800-c3a0-11ea-914b-51fde2ca373e.png)
Here is my config

**Comment by mydevbox** [comment]
I tried setting this up for about a week and was getting the same errors reported here by others.  I just tried again and it finally worked. Here's more info about the config that I finally got working. Hope it helps someone else.

`badnest:
  issue_token: "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=<REDACTED>&ss_domain=https%3A%2F%2Fhome.nest.com"
  cookie: "CONSENT=YES+US.en-GB+20170226-18-0; __Secure<REDACTED>SIDCC=<REDACTED>`

**Comment by colemamd** [comment]
I had this working last week, but a few days ago it went offline and am getting the same errors. 
HA error:
```
2020-09-06 23:53:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component badnest
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/badnest/__init__.py", line 32, in setup
    'api': NestAPI(
  File "/config/custom_components/badnest/api.py", line 114, in __init__
    self.login()
  File "/config/custom_components/badnest/api.py", line 147, in login
    r = self._session.get(url=self._issue_token, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1281, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.8/http/client.py", line 1213, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)
```

And my config:
```
badnest:
  issue_token: !secret nest_issue_token
  cookie: !secret nest_cookie
```
secrets:
```
nest_issue_token: https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token id_token&login_hint=<REDACTED>client_id=<REDACTED>&origin=https://home.nest.com&scope=openid profile email https://www.googleapis.com/auth/nest-account&ss_domain=https://home.nest.com
nest_cookie: 1P_JAR=2020-09-06-23; NID=204=<REDACTED>; SID=<REDACTED>; __Host-GAPS=<REDACTED>; __Secure-<REDACTED>; user_id=<REDACTED>
```

I did try putting the cookies into my config.yaml, in case there was a weird parsing error, but I got the same error. I've tried several times to update the cookies, but I keep getting the same error.

**Comment by mydevbox** [comment]
@colemamd I started getting this error again too. I repeated the steps to update my config and that got it working again. I compared the values and found that the issue_token url had not changed but, the cookie value had. My guess is that the cookie expires periodically and will require running thru the steps again when that happens.

**Comment by colemamd** [comment]
So I finally got it working again. I have been using FF to get the cookie. I tried using Chrome, noticed the cookie had a different format, so I used that and it works now.

**Comment by guice** [comment]
> I have been using FF to get the cookie. I tried using Chrome, noticed the cookie had a different format, so I used that and it works now.

This was my issue, too. Cookies within Firefox are still the `NID=` format, even after logging out and back in. It seems this new format is only visible in Chrome (I hadn't checked Opera or Safari).

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
