### ISSUE TITLE
Error in Home Assistant 0.112.2

### ISSUE THREAD

**Issue by Jaguaza** [mattsch/badnest#16]
Hello, since updating from 0.111 to 0.112 my nest thermostat does not work.  

It indicates this error to me.
Could you tell me where the error is please.

Detalles de registro (ERROR)
Logger: homeassistant.setup
Source: custom_components/badnest/api.py:154 
First occurred: 12:26:08 (1 occurrences) 
Last logged: 12:26:08

Error during setup of component badnest
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/badnest/__init__.py", line 34, in setup
    cookie,
  File "/config/custom_components/badnest/api.py", line 114, in __init__
    self.login()
  File "/config/custom_components/badnest/api.py", line 154, in login
    access_token = r.json()['access_token']
KeyError: 'access_token'

**Comment by mattsch** [comment]
I need to update code so it returns a proper error message, but that just means your existing auth is either expired or invalid. Should be fine once you generate a new set of credentials.

**Comment by Jaguaza** [comment]
> I need to update code so it returns a proper error message, but that just means your existing auth is either expired or invalid. Should be fine once you generate a new set of credentials.

Great thank you very much.  Very grateful for your work.

**Comment by tristan202** [comment]
Aquiring a new token/cookie pair did the trick. All working again.
