### ISSUE TITLE
Failed to load on undefined sensor_data['where_id']

### ISSUE THREAD

**Issue by maennes** [mattsch/badnest#17]
A new installation via HACS produced the following error message:
```
Logger: homeassistant.setup
Source: custom_components/badnest/api.py:389
First occurred: 2:51:58 PM (1 occurrences)
Last logged: 2:51:58 PM

Error during setup of component badnest
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/badnest/__init__.py", line 34, in setup
    cookie,
  File "/config/custom_components/badnest/api.py", line 116, in __init__
    self.update()
  File "/config/custom_components/badnest/api.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/config/custom_components/badnest/api.py", line 389, in update
    sensor_data['where_id']
KeyError: 'where_id'
```

This error went away after commenting out "kryptonite" from the definition of KNOWN_BUCKET_TYPES in custom_components/api.py (line 55).

**Comment by vkelly421** [comment]
Any update on getting the sensors bucket working? This fix works for me but temperature sensors obviously don't come through.

**Comment by mattsch** [comment]
I'm not using or maintaining this anymore since the combination of the native solution and homebridge plugin is far less fragile and actually works. I'll be updating this repo accordingly.
